name: Bug report
description: Create a bug report to help improve the library.
title: "[Bug]: "
labels:
  - bug
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: To Reproduce
      description: | 
        Steps to reproduce the behavior 
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true    

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the problem here.
    validations:
      required: false
