name: Feature request
description: Make a suggestion to improve the features in an existing library.
title: "[Enhancement]: "
labels:
  - enhancement
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: Please describe your suggestion and solution you would like to see.
      description: |
        A clear and concise description of what the suggestion is.
        
        - Provide a **step-by-step description of the suggested enhancement** in as many details as possible.
        - **Describe the current behavior** and **explain which behavior you expected to see instead** and why. At this point you can also tell which alternatives do not work for you.
        - **Explain why this enhancement would be useful** to most Jenkins Typescript Client users. You may also want to point out the other projects that solved it better and which could serve as inspiration.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
